import jwt from 'jsonwebtoken'
import { db } from '../db.js'

const JWT_SECRET = process.env.JWT_SECRET || 'rishikar-sports-super-secret-key-2026'

/**
 * Generate a JWT token for a user or admin
 */
export function generateToken(payload, expiresIn = '30d') {
  return jwt.sign(payload, JWT_SECRET, { expiresIn })
}

/**
 * Middleware: Verify user is logged in
 */
export function requireAuth(req, res, next) {
  try {
    const authHeader = req.headers.authorization
    if (!authHeader || !authHeader.startsWith('Bearer ')) {
      return res.status(401).json({ success: false, message: 'Authorization token missing or invalid' })
    }

    const token = authHeader.split(' ')[1]
    const decoded = jwt.verify(token, JWT_SECRET)
    req.user = decoded
    next()
  } catch (err) {
    return res.status(401).json({ success: false, message: 'Invalid or expired token', error: err.message })
  }
}

/**
 * Middleware: Verify user is an Admin
 * Accepts either:
 * 1) Bearer JWT token with role === 'admin'
 * 2) Legacy/Direct Admin PIN header `x-admin-pin` matching settings.adminPin
 */
export function requireAdmin(req, res, next) {
  try {
    const settings = db.getSettings()

    // 1. Check custom admin PIN header
    const pinHeader = req.headers['x-admin-pin']
    if (pinHeader && String(pinHeader).trim() === String(settings.adminPin).trim()) {
      req.user = { role: 'admin', name: 'Store Admin' }
      return next()
    }

    // 2. Check Bearer token
    const authHeader = req.headers.authorization
    if (authHeader && authHeader.startsWith('Bearer ')) {
      const token = authHeader.split(' ')[1]

      // Support direct token generated by /api/admin/login
      if (token.startsWith('rs_adm_')) {
        req.user = { role: 'admin', name: 'Store Admin' }
        return next()
      }

      // Verify JWT
      try {
        const decoded = jwt.verify(token, JWT_SECRET)
        if (decoded.role === 'admin') {
          req.user = decoded
          return next()
        }
      } catch {
        // Fall through to 403
      }
    }

    return res.status(403).json({
      success: false,
      message: 'Access Denied: Admin authorization required to perform this action',
    })
  } catch (err) {
    return res.status(500).json({ success: false, message: 'Auth check error', error: err.message })
  }
}

/**
 * Middleware: Optional Auth (if token present, attaches req.user, otherwise continues)
 */
export function optionalAuth(req, res, next) {
  try {
    const authHeader = req.headers.authorization
    if (authHeader && authHeader.startsWith('Bearer ')) {
      const token = authHeader.split(' ')[1]
      req.user = jwt.verify(token, JWT_SECRET)
    }
  } catch {
    // Continue without req.user
  }
  next()
}
